// Objectif : implémenter la frontière de décision métier propre au dépôt.
export const OUTCOMES=["favorable","favorable_with_redactions","unfavorable","out_of_scope","unclear"];
export function accessRequest(input){if(!input?.id || !input?.administration || !input?.document || !input?.receivedAt)
  throw new TypeError("A request needs id, administration, document and receivedAt");const date=new Date(input.receivedAt);if(Number.isNaN(date.valueOf()))throw new TypeError("receivedAt must be an ISO date");
  return{id:String(input.id),administration:String(input.administration),document:String(input.document).trim(),context:String(input.context||""),receivedAt:date.toISOString()};}
export function cadaPrecedent(input){if(!input?.reference || !input?.sessionDate || !input?.administration || !input?.conclusion || !input?.text || !input?.sourceUrl)
  throw new TypeError("A precedent needs reference, sessionDate, administration, conclusion, text and sourceUrl");const date=new Date(input.sessionDate);if(Number.isNaN(date.valueOf()))throw new TypeError("sessionDate must be an ISO date");
  return{reference:String(input.reference),sessionDate:date.toISOString(),administration:String(input.administration),theme:String(input.theme||""),keywords:[...(input.keywords||[])].map(String),conclusion:String(input.conclusion),text:String(input.text),sourceUrl:String(input.sourceUrl)};}
export async function triageRequest(requestInput,precedentInput,provider){const request=accessRequest(requestInput),precedent=cadaPrecedent(precedentInput);
  const response=await provider.decide({state:{request,precedent},questions:{outcome:{type:"choice",instructions:"Use only the supplied precedent to prepare a triage hypothesis. favorable_with_redactions covers partial communication after protected material is removed. Choose unclear whenever facts or current law are insufficient.",criteria:{favorable:"The precedent supports communication",favorable_with_redactions:"Communication appears possible only after redaction or separation",unfavorable:"The precedent supports refusal",out_of_scope:"The requested material appears outside CADA access rules",unclear:"Insufficiently analogous or incomplete"}},analogy:{type:"score",instructions:"Score factual and documentary similarity to the precedent, not legal certainty.",criteria:["0 — different issue","1 — weak analogy","2 — useful analogy","3 — very close analogy"]}}});
  const outcome=response.answers.outcome,analogy=response.answers.analogy;return{outcome:outcome.choice,probability:outcome.probabilities[outcome.choice],analogy:analogy.score,confidence:Math.min(outcome.confidence,analogy.confidence),review:true,legalAdvice:false,request,precedent,usage:response.usage};}
